spring:
  cloud:
    gateway:
      routes:
        - id: msvc-products
          uri: lb://msvc-products
          predicates:
            - Path=/api/products/**
#            - Header=token, 12345
#            - Method=GET, POST
#            - Query=color, verde #ESTOS SON QUERY PARAMS
#            - Cookie=color, red
          filters:
            - StripPrefix=2
            - name: SampleCookie
              args:
                message: Mensaje de la cookie q chimba, PRODUCTOS
                name: user
                value: JuanitoJose
        - id: msvc-items
          uri: lb://msvc-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, juanjo
            - AddResponseHeader=token-response, 1234567
            - AddRequestParameter=name, Value

