networks:
  springcloud:

services:
  config-server:
    container_name: config-server
    image: config-server:v1
    ports:
      - "8888:8888"
    restart: always #si falla sigue intentando levantarlo
    networks:
      - springcloud
  spring-eureka:
    container_name: spring-eureka
    image: eureka-server:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  mysql8:
    container_name: mysqlspring
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    networks:
      - springcloud
    #VARIABLES DE ENTORNO
    environment:
      - MYSQL_DATABASE=db_springboot_cloud
      - MYSQL_ROOT_PASSWORD=JAJEJA2121
  zipkin-server:
    container_name: zipkin-server
    image: zipkin-server:v1
    ports:
      - "9411:9411"
    restart: always
    networks:
      - springcloud
    #VARIABLES DE ENTORNO
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_USER=urlruraqazplhpoa
      - MYSQL_PASS=k9cljVhBmEu1yvilIPoD
      - MYSQL_DB=bq3wnnen5rbatel2fp74
      - MYSQL_HOST=bq3wnnen5rbatel2fp74-mysql.services.clever-cloud.com
  msvc-products:
    container_name: msvc-products
    image: msvc-products:v1
    ports:
      - "8001:8001"
    restart: always
    networks:
      - springcloud
    #COSAS DE LAS QUE DEPENDE ESTE CONTENEDOR(No se levantara hasta que lo que lo alimenta se levante
    depends_on:
      - spring-eureka
      - zipkin-server
  msvc-items:
    container_name: msvc-items
    image: msvc-items:v1
    ports:
      - "8002:8002"
    restart: always
    networks:
      - springcloud
    #COSAS DE LAS QUE DEPENDE ESTE CONTENEDOR(No se levantara hasta que lo que lo alimenta se levante
    depends_on:
      - spring-eureka
      - zipkin-server
  oauth-server:
    container_name: oauth-server
    image: oauth-server:v1
    ports:
      - "9100:9100"
    restart: always
    networks:
      - springcloud
    #COSAS DE LAS QUE DEPENDE ESTE CONTENEDOR(No se levantara hasta que lo que lo alimenta se levante
    depends_on:
      - spring-eureka
      - zipkin-server
      - msvc-users
  msvc-users:
    container_name: msvc-users
    image: msvc-users:v1
    ports:
      - "6666:6666"
    restart: always
    networks:
      - springcloud
    #COSAS DE LAS QUE DEPENDE ESTE CONTENEDOR(No se levantara hasta que lo que lo alimenta se levante
    depends_on:
      - spring-eureka
      - zipkin-server
  gateway-server:
    container_name: gateway-server
    image: gateway-server:v1
    ports:
      - "8090:8090"
    restart: always
    networks:
      - springcloud
    environment:
      #VARIABLE RARA QUE TOCA PONER CON LA IP LOCAL
      IP_ADDR: http://192.168.1.133:9100
    #COSAS DE LAS QUE DEPENDE ESTE CONTENEDOR(No se levantara hasta que lo que lo alimenta se levante
    depends_on:
      - spring-eureka
      - zipkin-server
      - msvc-users
      - msvc-products
      - msvc-items
      - oauth-server
