networks:
  springclouddeploy:

services:
  spring-eureka:
    container_name: spring-eureka
    image: jarenas1/eureka-server-jarenas1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springclouddeploy
  msvc-products:
    container_name: msvc-products
    image: jarenas1/msvc-products-jarenas1
    ports:
      - "8001:8001"
    restart: always
    networks:
      - springclouddeploy
    #COSAS DE LAS QUE DEPENDE ESTE CONTENEDOR(No se levantara hasta que lo que lo alimenta se levante
    depends_on:
      - spring-eureka
  msvc-items:
    container_name: msvc-items
    image: jarenas1/msvc-items-jarenas1
    ports:
      - "8002:8002"
    restart: always
    networks:
      - springclouddeploy
    #COSAS DE LAS QUE DEPENDE ESTE CONTENEDOR(No se levantara hasta que lo que lo alimenta se levante
    depends_on:
      - spring-eureka

